# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medicacion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paciente',
            field=models.CharField(default='', max_length=200),
        ),
    ]
