# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('e', 'Emitido'), ('t', 'En Transito'), ('f', 'Firmado'), ('pr', 'Presentado'), ('pa', 'Pago')], default='e', help_text='Estado del pedido', max_length=2),
        ),
    ]
