# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20180203_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='medico',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='paciente',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
