# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20180204_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.AutoField( primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='paciente',
            field=models.CharField(default='', max_length=200),
        ),
    ]
