# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 22:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20180204_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefono en el formato: '+999999999'. Hasta 15 digitos.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dni',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dosis',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('EM', 'Emitido'), ('TR', 'En Transito'), ('FI', 'Firmado'), ('PR', 'Presentado'), ('PA', 'Pago')], default='e', help_text='Estado del pedido', max_length=2),
        ),
        migrations.AddField(
            model_name='pedido',
            name='farmacia',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_farmaceutica',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_afiliado',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
