# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20180205_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dosis',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='farmacia',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_farmaceutica',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
