# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20180207_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('EM', 'Emitido'), ('TR', 'En Transito'), ('FI', 'Firmado'), ('PR', 'Presentado'), ('PA', 'Pago')], default='EM', help_text='Estado del pedido', max_length=2),
        ),
    ]
