# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_auto_20180207_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': (('can_create', 'Puede hacer pedidos'), ('can_edit', 'Puede editar el estado'))},
        ),
    ]
