# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_auto_20180212_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.ForeignKey(default='+000', on_delete=django.db.models.deletion.CASCADE, to='pedido.PhoneModel'),
        ),
    ]
