# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_pedido_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='name',
            field=models.CharField(default='Ciudad Autonoma de Buenos Aires', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, default='-', max_length=17),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='name',
            field=models.CharField(default='Capital Federal', max_length=50),
        ),
    ]
